const GigActionsTypes = {
  // SELLER ACTIONS
  LIST_GIG: "LIST_GIG", 
  UNLIST_GIG: "UNLIST_GIG",
  DELIVER: "DELIVER",
  CLAIM_PAYMENT: "CLAIM_PAYMENT",

  // BUYER ACTIONS
  ORDER_GIG: "ORDER_GIG",
  CANCEL_ORDER: "CANCEL_ORDER",
  DISPUTE_GIG: "DISPUTE_GIG",
  ACCEPT_DELIVERY: "ACCEPT_DELIVERY"
}